### ISSUE TITLE
Windows 版本是不是滞后于 Linux 版本啊？

### ISSUE THREAD

**Issue by yiding-he** [ideawu/ssdb-bin#8]
能不能给个最新的 Windows 版本？就算是开发调试用也是需要的。

**Comment by BigJoe01** [comment]
https://github.com/ideawu/ssdb-bin
ssdb windows client
https://github.com/BigJoe01/ssdb_client

**Comment by ideawu** [comment]
win版开发调试没问题。不知道你遇到什么问题？
